{% set version = "2.74" %}

package:
  name: libcap
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-{{ version }}.tar.xz
  sha256: eb85271f2893188644b6451cec8ce99f4541498f16ff9f84877c2fc872717714

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('libcap', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - attr

test:
  commands:
    - test -f "$PREFIX/lib/libcap.so"

about:
  home: https://directory.fsf.org/wiki/Libcap
  license: BSD-3-Clause
  license_family: BSD
  license_file: License
  summary: Implements the user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels

extra:
  recipe-maintainers:
    - scopatz
    - ehfd
