{% set name = "libcap" %}
{% set version = "2.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-{{ version }}.tar.xz
  sha256: d83dc701c5a3a3d726c0a907714886af535b326c32501ab96831847949803297

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libcap', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - attr

test:
  commands:
    - test -f "$PREFIX/lib/libcap.so"

about:
  home: https://directory.fsf.org/wiki/Libcap
  license: BSD-3-Clause
  license_family: BSD
  license_file: License
  summary: Implements the user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels

extra:
  recipe-maintainers:
    - scopatz
