bot: {automerge: true}
conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
